### ISSUE TITLE
Mercari US Api Changes

### ISSUE THREAD

**Issue by Kuuuube** [marvinody/mercarius#3]
Just a heads up, Mercari US has changed their api to require "authentication" in a similar way to Mercari JP. But it's different enough to not work with the Mercari JP method.

**Comment by marvinody** [comment]
well, that sounds painfully fun...

I'll take a look when I have time to see if I can figure it out.

**Comment by Kuuuube** [comment]
Thank you! It works. 

If you would like I can send you a pr whenever I notice the hash changes. I think it changes every few months. 

There were a few changes between the previous hash this repo had and the one you updated to just now. Since they're so easy to figure out and don't change too frequently I didn't think much of it.

**Comment by marvinody** [comment]
That is fine with me. If it's only every few months, I think updating it manually isn't too much of an issue. It's my first time dealing with this persistent hash thing for graphql so I'm a bit lost on the specifics.

Just ping me in the PRs when you open them since I'm not sure if I get notifications for them by default. Happy to approve & publish.
